#diccionario para cargar la información de los códigos de patología que
#carencen de descripción.
map_cie_cod={
    'A071':'Giardiasis [lambliasis]',
    'B11':'n/a',
    "B82":"Parasitosis intestinal, sin otra especificación",
    'B20':'Enfermedad por virus de la inmunodeficiencia humana [VIH], resultante en enfermedades infecciosas y parasitarias',
    'B84':'n/a',
    'B084':'Estomatitis vesicular enteroviral con exantema',
    'C61':'Tumor maligno de la próstata',
    'E039':'Hipotiroidismo',
    "E027":"n/a",
    'E08':'n/a',
    'E444':'Desnutrición proteicocalórica de grado moderado y leve',
    'F441':'Fuga disociativa',
    'F450':'Trastorno de somatización',
    'G510':'Parálisis de Bell',
    "G51":'Trastornos del nervio facial',
    'H13':'Trastornos de la conjuntiva en enfermedades clasificadas en otra parte',
    'H15':'Trastornos de la esclerótica',
    'H650':'Otitis media aguda serosa',
    'H660':'Otitis media supurativa aguda',
    'H67':'Otitis media en enfermedades clasificadas en otra parte',
    'I499':'Arritmia cardíaca, no especificada',
    'I59':'n/a',
    'I519':'Enfermedad cardíaca, no especificada',
    'I639':'Infarto cerebral, no especificado',
    'I959':'Hipotensión, no especificada',
    'J09':'Influenza debida a virus de la influenza aviar identificado',
    'J12':'	Neumonía viral, no clasificada en otra parte',
    'J81':'Edema pulmonar',
    'K080':'Exfoliación de los dientes debida a causas sistémicas',
    'K104':'n/a',
    'K295':'Gastritis crónica, no especificada',
    'K746':'Otras cirrosis del hígado y las no especificadas',
    'K760':'Degeneración grasa del hígado, no clasificada en otra parte',
    'K819':'Colecistitis, no especificada',
    'L739':'Trastorno folicular, no especificado',
    'M515':'n/a',
    'M624':'Contractura muscular',
    'M67':'Otros trastornos de la sinovia y del tendón',
    'M796':'Dolor en miembro',
    'M910':'Osteocondrosis juvenil de la pelvis',
    'N11':'Nefritis tubulointersticial crónica',
    'N12':'Nefritis tubulointersticial, no especificada como aguda o crónica',
    'N391':'Proteinuria persistente, n o especificada',
    'N481':'Balanopostitis',
    'N951':'Estados menopáusicos y climatéricos femeninos',
    'R011':'Soplo cardíaco, no especificado',
    'R07':'Dolor de garganta y en el pecho',
    'R088':'n/a',
    'R252':'Calambres y espasmos',
    'R702':'n/a',
    'R78':'Hallazgo de drogas y otras sustancias que normalmente no se encuentran en la sangre',
    'S019':'Herida de la cabeza, parte no especificada',
    'S06':'Traumatismo intracraneal',
    "S401":'n/a',
    "S49":"Otros traumatismos y los no especificados del hombro y del brazo",
    "S69":"Otros traumatismos y los no especificados de la muñeca y de la mano",
    "S71":"Herida de la cadera y del muslo",
    "S89":"Otros traumatismos y los no especificados de la pierna",
    "S99":"Otros traumatismos y los no especificados del pie y del tobillo",
    "T171":"Cuerpo extraño en el orificio nasal",
    "T418":"n/a",
    "T670":"Golpe de calor e insolación",
    "T74":"Síndrome del maltrato",
    "T784":"Alergia no especificada",
    "U19":"n/a",
    "U59":"n/a",
    "U60":"n/a",
    "U61":"n/a",
    "U62":"n/a",
    "U63":"n/a",
    "U64":"n/a",
    "U67":"n/a",
    "V206":"n/a",
    "Y20":"Ahorcamiento, estrangulamiento y sofocación, de intención no determinada",
    "Y30":"Caída, salto o empujón desde lugar elevado, de intención no determinada",
    "Z14":"n/a",
    "Y40":"Efectos adversos de antibióticos sistémicos",
    "Y45":"Efectos adversos de drogas analgésicas, antipiréticas y antiinflamatorias",
    "Z300":"Consejo y asesoramiento general sobre la anticoncepción",
    "Z38":"Nacidos vivos según lugar de nacimiento",
    "Z71":"Personas en contacto con los servicios de salud por otras consultas y consejos médicos, no clasificados en otra parte",
    "Z73":"	Problemas relacionados con dificultades con el modo de vida",
    "nan":"n/a"

}

#creamos el diccionario para unificar los nombres y realizar el proceso
dict_transformacion_saps={
"Dr. CALMANASH": "Dr. Saul Calmanash",
"Dr. Saul Calmanash":"Dr. Saul Calmanash",
"DR. GUILLERMO RAWSON": "Dr. Guillermo Rawson",
"Dr. Guillermo Rawson":"Dr. Guillermo Rawson",
"SANTA RITA":"Dr. Jose de los Reyes Vidal",
"Dr. Jose de los Reyes Vidal":"Dr. Jose de los Reyes Vidal",
"RAWSON":"Dr. Guillermo Rawson",
"Cichero": "Dr. Romilio Monzón",
"CICHERO":"Dr. Romilio Monzón",
"Dr. ROMILIO MONZÓN":"Dr. Romilio Monzón",
"Dr. Romilio Monzón":"Dr. Romilio Monzón",
"CAÑADA QUIROZ":"Dr. Marcelino Vera",
"Dr. Marcelino Vera":"Dr. Marcelino Vera",
"DR MANUEL A. GONZALEZ":"Dr. Manuel Gonzalez",
"Dr. Manuel Gonzalez":"Dr. Manuel Gonzalez",
"DR. ALBERTO LIFSCHITZ":"Dr. Lifschitz",
"Dr. Lifschitz":"Dr. Lifschitz",
"DR. ANIBAL MALVIDO":"Dr. Anibal Malvido",
"Dr. Anibal Malvido":"Dr. Anibal Malvido",
"DR. BENJAMIN SERRANO":"Dr. Benjamin Serrano",
"Dr. Benjamin Serrano":"Dr. Benjamin Serrano",
"DR. FLIER": "Dr. JC Benitez Suarez",
'LOMAS':"Dr. JC Benitez Suarez",
"Dr. JC Benitez Suarez":"Dr. JC Benitez Suarez",
"DR. JOSE DE LOS REYES VIDAL":"Dr. Jose de los Reyes Vidal",
"Dr. Jose de los Reyes Vidal":"Dr. Jose de los Reyes Vidal",
"DR. KORIMBLUM": "Dr. Korimblum",
"Dr. Korimblum":"Dr. Korimblum",
"Dr. Manuel Cassuso":"Dr. Manuel Cassuso",
"DR. MANUEL CASSUSO":"Dr. Manuel Cassuso",
"DR. MAURICIO OPEN": "Dr. Mauricio Open",
"Dr. Mauricio Open":"Dr. Mauricio Open",
"DR. PEDRO BLUGERMAN":"Dr. Pedro Blugerman",
"Dr. Pedro Blugerman":"Dr. Pedro Blugerman",
"DR. PIRCHI":"Dr. Oscar Pirchi",
"Dr. Oscar Pirchi":"Dr. Oscar Pirchi",
"DR. ROSSI CANDIA":"Dr. Miguel Rossi Candia",
"Dr. Miguel Rossi Candia":"Dr. Miguel Rossi Candia",
"Dr. SANTIAGO LORENZO":"Dr. Santiago Lorenzo",
"Dr. Santiago Lorenzo":"Dr. Santiago Lorenzo",
"DR. SEMPER":"Dr. Semper",
"Dr. Semper":"Dr. Semper",
"DR. SUSSINI":"Dr. Sussini",
"Dr. Sussini":"Dr. Sussini",
"ESPERANZA":"Esperanza",
"Esperanza":"Esperanza",
"GDOR. ELIAS GALVAN":"Dr. Elias Galvan",
"Dr. Elias Galvan":"Dr. Elias Galvan",
"GÜEMES":"Guemes",
"Guemes":"Guemes",
"ITATI":"Itati",
"Itati":"Itati",
"MARCELINO VERA":"Dr. Marcelino Vera",
"Dr. Marcelino Vera":"Dr. Marcelino Vera",
"PASO MARTINEZ":"Paso Martinez",
"Paso Martinez":"Paso Martinez",
"PRIMERA JUNTA":"Primera Junta",
"Primera Junta":"Primera Junta",
"PUJOL":"Pujol",
"Pujol":"Pujol",
"QUINTA FERRE":"Quinta Ferre",
"Quinta Ferre":"Quinta Ferre",
"RIO PARANA":"Rio Parana",
"Rio Parana":"Rio Parana",
"SAN MARCOS":"San Marcos",
"San Marcos":"San Marcos",
"SANTA MARGARITA":"Santa Margarita",
"Santa Margarita":"Santa Margarita",
"SANTA MARTA":"Santa Marta",
"Santa Marta":"Santa Marta",
"VILLA CHIQUITA":"Villa Chiquita",
"Villa Chiquita":"Villa Chiquita",
"VILLA GARCIA":"Villa Garcia",
"Villa Garcia":"Villa Garcia",
"DR. CHERCOFF":"Dr. Juan Chercoff",
"Dr. Juan Chercoff":"Dr. Juan Chercoff",
"SANTA CATALINA":"Santa Catalina",
"Santa Catalina":"Santa Catalina",
"OPERATIVOS TERRITORIALES":"OPERATIVO TERRITORIALES",
"n/a":"n/a",
"CENTRO DE DIST. DE VACUNAS":"Centro de distribucion de Vacunas",
"Centro de distribucion de Vacunas":"Centro de distribucion de Vacunas",
"SAPUCAY":"Sapucay",
"Sapucay":"Sapucay"
}

#mapeo de nombres para los tipos de vacunas
map_tipo_vac = {
    "ANTI GRIPAL ADULTO": "ANTIGRIPAL ADULTO",
    "GRIPR A": "GRIPE A",
    "ANTI AMARILLICA": "FIEBRE AMARILLA",
    "NEUMO 13 ": "NEUMO13",
    "NEUMO 13": "NEUMO13",
    "NEUMO 23": "NEUMO23",
    "PREV 13":"PREVENAR 13",
    "OTROS":"OTRAS",
    "ANTI GRIPAL PEDIATRICO":"ANTIGRIPAL PEDIATRICO",
    "ANTIGRIPAL PEDIA.":"ANTIGRIPAL PEDIATRICO",
    "ANTIGRIPAL PEDITRICO": "ANTIGRIPAL PEDIATRICO",
    "ANTIPEDIATRICO":"ANTIGRIPAL PEDIATRICO",
    "ANT. PEDIAYTICO": "ANTIGRIPAL PEDIATRICO",
    "ANT. PEDIAT.": "ANTIGRIPAL PEDIATRICO",
    "ANT. PEDIATRICO": "ANTIGRIPAL PEDIATRICO",
    "ANTI GRIPAL":"ANTIGRIPAL",
    "BEXSERRO":"BEXSERO",
    "FLUXVIRG":"FLUXVIR"
}